### ISSUE TITLE
Missing clothing: Splatfest Tee

### ISSUE THREAD

**Issue by silentj** [DeviPotato/splat2-calc#9]
I was going to check out my stats with [the Splatfest Tee](https://splatoonwiki.org/wiki/Splatfest_Tee) but it doesn't appear to be selectable. Adding that may be a bit annoying because it also has the unique main ability [Ability Doubler](https://splatoonwiki.org/wiki/Ability_Doubler).

**Comment by DeviPotato** [comment]
Hey there.

I had thought about the Splatfest Tee and initially left it out mostly because it seemed situational - generally you can't "plan ahead" the abilities for the Splatfest Tee, and it's frequently scrubbed.

However, I can see the benefits of this. It won't be too hard to implement. I'll see what I can do.

**Comment by DeviPotato** [comment]
Added this today!

**Comment by silentj** [comment]
Excellent! Thank you!
